<?php return array (
  'WEB_TITLE' => '靖多鱼科技有限公司',
  'WEB_COMPANY' => '靖多鱼科技有限公司',
  'DOMAIN_NAME' => 'https://www.phpdecode.cn',
  'RECORD' => 'qq：994743720  新月  php web',
  'ICP' => '蜀ICP备19023826号',
  'COPY' => '郭靖',
  'WEB_ON' => '1',
  'WEB_COUNTCODE' => '                    <div class="copyright-txt">
                        备案号：蜀ICP备19023826号   
                    </div>
',
  'VERSION' => '1.0版',
  'WEB_KEYWORDS' => 'php开发，web',
  'WEB_DESCRIPTION' => 'php thinkphp web html js bootstrap',
  'REG_ON' => '1',
  'WEB_IP_STATE' => '0',
  'REG_POINT' => '10',
  'WEB_MAIN_DOMAIN' => 'mall',
  'CODE_CURVE' => '1',
  'CODE_LEN' => '4',
  'SHOW_VERIFY' => '1',
  'CODE_NOISE' => '1',
  'HOME_SHOW_VERIFY' => '0',
  'CODE_FONT_SIZE' => '30',
  'UPLOAD_PATH' => './upload/',
  'UPLOAD_TYPE' => 'jpg,png,jpeg',
  'WEB_STYLE' => 'default',
  'WEB_STORE_DIR' => 'store',
  'SMS_ACCOUNT_SID' => 'f581c3b503eb86c94813e7edfc10910a',
  'SMS_TOKEN' => '6e9b9a7524dffc62e5b7c4d0c75c2e89',
  'SMS_APP_ID' => '2a5fd81b17de45ffab11ffbcfb14f5ec',
  'EMAIL_SMTP_DEBUG' => '0',
  'EMAIL_DEBUG_OUTPUT' => 'html',
  'EMAIL_HOST' => 'smtp.qq.com',
  'EMAIL_SMTP_SECURE' => 'ssl',
  'EMAIL_PORT' => '465',
  'EMAIL_SMTP_AUTH' => '1',
  'EMAIL_USERNAME' => '994743720@qq.com',
  'EMAIL_PASSWORD' => 'jcfdbjojjmjvbbcg',
  'EMAIL_SETFROM_ADDRESS' => '994743720@qq.com',
  'EMAIL_SETFROM_NAME' => '靖多鱼',
  'EMAIL_ADDREPLY_TO_ADDRESS' => '994743720@qq.com',
  'EMAIL_ADDREPLY_TO_NAME' => '靖多鱼',
  'ORDER_OVER_PAY' => '86400*30',
  'ORDER_CONFIRM_PAY' => '86400*30',
  'ORDER_RETURN_TIME' => '86400*30',
)
?>