<?php return array (
  'WEB_TITLE' => '多店铺商城',
  'WEB_COMPANY' => '公司名称',
  'DOMAIN_NAME' => 'https://www.baidu.com',
  'RECORD' => 'qq：994743720  新月  php web',
  'ICP' => 'ICP备19023826号',
  'COPY' => '  https://www.baidu.com ',
  'WEB_ON' => '1',
  'WEB_COUNTCODE' => '                    <div class="copyright-txt">
                        备案号：蜀ICP备19023826号   
                    </div>
',
  'VERSION' => 'beta 1.0',
  'WEB_KEYWORDS' => 'php开发，web',
  'WEB_DESCRIPTION' => 'php thinkphp web html js bootstrap',
  'REG_ON' => '1',
  'WEB_IP_STATE' => '0',
  'REG_POINT' => '10',
  'WEB_MAIN_DOMAIN' => 'mall',
  'CODE_CURVE' => '0',
  'CODE_LEN' => '4',
  'SHOW_VERIFY' => '1',
  'CODE_NOISE' => '1',
  'HOME_SHOW_VERIFY' => '0',
  'CODE_FONT_SIZE' => '30',
  'UPLOAD_PATH' => './upload/',
  'UPLOAD_TYPE' => 'jpg,png,jpeg',
  'WEB_STYLE' => 'default',
  'WEB_STORE_DIR' => 'store',
  'SMS_ACCOUNT_SID' => 'a1979e260cf49cbec7ad31f99734ed93',
  'SMS_TOKEN' => '25798be441257d1ea1a6b105664c3840',
  'SMS_APP_ID' => '9e72c6afaa5748d09cf2035258f613ed',
  'EMAIL_SMTP_DEBUG' => '0',
  'EMAIL_DEBUG_OUTPUT' => 'html',
  'EMAIL_HOST' => 'smtp.qq.com',
  'EMAIL_SMTP_SECURE' => 'ssl',
  'EMAIL_PORT' => '465',
  'EMAIL_SMTP_AUTH' => '1',
  'EMAIL_USERNAME' => '994743720@qq.com',
  'EMAIL_PASSWORD' => 'bdrufxdqjreybceb',
  'EMAIL_SETFROM_ADDRESS' => '994743720@qq.com',
  'EMAIL_SETFROM_NAME' => 'baidu.com',
  'EMAIL_ADDREPLY_TO_ADDRESS' => '994743720@qq.com',
  'EMAIL_ADDREPLY_TO_NAME' => 'jinggithub',
  'ORDER_OVER_PAY' => '86400*30',
  'ORDER_CONFIRM_PAY' => '86400*30',
  'ORDER_RETURN_TIME' => '86400*30',
)
?>